### ISSUE TITLE
Providing mchess-21 to mchess-29

### ISSUE THREAD

**Issue by JoanThibault** [marijnheule/mchess#1]
Hi,

Would you mind providing the benchmark set between mchess-20 and mchess-30 ?
(that or the instance generator)
I have been working on a small BDD-based SAT-solver [*Snowflake*](https://gitlab.com/boreal-ldd/snowflake) and it manages to solve mchess-20 in about 20s but fails for mchess-30 (memory out after 10 minutes).
Therefore I'd like to get a better understanding of what goes wrong.

Best,

Joan

**Comment by marijnheule** [comment]
Hi Joan,

Please check out Randy's GitHub on BDDs for mutilated chessboard and other problems: https://github.com/rebryant/pgbdd

In that repository, you can find a generator for the mchess formulas in the benchmark directory.
./chess.py -r mchess-21 -n 21

Best regards,

Marijn

**Comment by JoanThibault** [comment]
Thank you for the link, I will look into it =)
Best,
Joan
